version: '0.20.1.{build}'

branches:
  only:
  - master
  - vNext

skip_tags: true

clone_folder: C:\projects\libgit2sharp

environment:
  matrix:
  - xunit_runner: xunit.console.clr4.exe
    Arch: 64
  - xunit_runner: xunit.console.clr4.x86.exe
    Arch: 32

matrix:
  fast_finish: true

assembly_info:
  patch: true
  file: LibGit2Sharp\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'

cache:
  - packages

build_script:
- nuget restore "C:\projects\libgit2sharp\LibGit2Sharp.sln"
- msbuild "C:\projects\libgit2sharp\LibGit2Sharp.sln" /verbosity:normal /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /property:ExtraDefine="LEAKS_IDENTIFYING"

test_script:
- '%xunit_runner%  "C:\projects\libgit2sharp\LibGit2Sharp.Tests\bin\Release\LibGit2Sharp.Tests.dll" /appveyor'
- IF %ERRORLEVEL% NEQ 0 EXIT /B %ERRORLEVEL%

on_success:
- ps: >-

    "C:\projects\libgit2sharp\nuget.package\BuildNugetPackage.ps1" "$($env:APPVEYOR_REPO_COMMIT)"

notifications:
- provider: Email
  to:
    - emeric.fermas@gmail.com
  on_build_status_changed: true
